# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RGB2D' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for RGB2D
  pod 'Firebase/Core'
  pod 'Firebase/Database'  

  target 'RGB2DTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RGB2DUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
